[msg MSG_GAMESTART [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Let's start up FreeDOOM.[n][f 1 3 65535][w][e]

[msg MSG_GAMESTART_NULL]
[s][vp 8 2 0 91 65535 0]Time to play FreeDOOM...[n][f 1 3 65535][w][e]

[msg MSG_MorganaSass [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 1026 65535 0]C'mon dude, I think you can play this game[n]with a little more challenge.[n][f 1 3 65535][w][e]

[msg MSG_StageClear [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1183 65535 0]Hey, you actually managed to[n]play the game normally! Good one.[n][f 1 3 65535][w][e]

[msg MSG_MorganaImpressed [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1183 65535 0]Now that was a challenge! Color me impressed,[n]that really is a hard difficulty.[n][f 1 3 65535][w][e]

[msg MSG_MorganaShocked [Morgana]]
[s][bup 0 3 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 1039 65535 0]W-wow, you played on the toughest difficulty...[n]You're a lot braver than I![n][f 1 3 65535][w][e]

[msg MND_Unimpressed]
[s][vp 8 2 0 95 65535 0]I feel like I could've played[n]on a higher difficulty...[n][f 1 3 65535][w][e]

[msg MND_StageClear]
[s][vp 8 2 0 93 65535 0]I beat the stage...![n][f 1 3 65535][w][e]

[msg MND_Impressed]
[s][vp 8 2 0 98 65535 0]I played on a hard difficuty,[n]that was quite a challenge...[n][f 1 3 65535][w][e]

[msg MND_Shocked]
[s][vp 8 2 0 99 65535 0]Woah, I managed to survive the[n]toughest difficulty...[n][f 1 3 65535][w][e]

[msg MSG_StageGameOver [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 1169 65535 0]...Well that's disappointing.[n]You didn't even clear a level.[n][f 1 3 65535][w][e]

[msg MND_StageGameOver]
[s][vp 8 2 0 87 65535 0]I couldn't clear a single level...[n][f 1 3 65535][w][e]

[msg MSG_018_GUTS_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]I bet killing all those imps and demons[n]increased your [stIcon 3][clr 26][stLabel 3][clr 27].[n][f 1 3 65535][w][e]

[msg MSG_018_PROFGUTS_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]I bet killing so many imps and demons[n]increased your [stIcon 2][clr 26][stLabel 2][clr 27][n]and [stIcon 3][clr 26][stLabel 3][clr 27].[n][f 1 3 65535][w][e]

[msg MND_018_GUTS_0]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]It feels like fighting the imps and demons[n]has increased my [stIcon 3][clr 26][stLabel 3][clr 27]...[n][f 1 3 65535][w][e]

[msg MND_018_PROFGUTS_0]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]It feels like fighting the imps and demons[n]has increased my [stIcon 2][clr 26][stLabel 2][clr 27][n]and [stIcon 3][clr 26][stLabel 3][clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_FAILED_UP [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Well even then, you showed some [stIcon 3][clr 26][stLabel 3][clr 27][n]just for trying at least.[n][f 1 3 65535][w][e]

[msg MND_FAILED_UP]
[s][vp 8 2 0 0 65535 0]I failed, but I think my [stIcon 3][clr 26][stLabel 3][clr 27][n]still increased a little thanks[n]to my attempt.[n][f 1 3 65535][w][e]

[msg MSG_BABY_EASY_FAILED_UP [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You might've only played a few levels on the[n]easier difficulties, but it seems fighting the[n]enemy still increased your [stIcon 3][clr 26][stLabel 3][clr 27] somehow.[n][f 1 3 65535][w][e]

[msg MND_BABY_EASY_FAILED_UP]
[s]I might've only played a few levels on the easier difficulties,[n]but it seems fighting the enemy still[n]increased my [stIcon 3][clr 26][stLabel 3][clr 27] a little.[n][f 1 3 65535][w][e]

[msg MSG_GAME_END_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1175 65535 0]Well, it's getting late. Let's head[n]to sleep soon, okay?[n][f 1 3 65535][w][e]

[msg MND_GAME_END_NULL]
[s][vp 8 2 0 94 65535 0]It's getting late...[n]I should head to bed.[n][f 1 3 65535][w][e]

[msg MSG_GAME_END_MORU_DAY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1175 65535 0]That took a really long time...[n]We should probably stop playing[n]games for now, don't you think?[n][f 1 3 65535][w][e]

[msg MND_GAME_END_NULL_DAY]
[s][vp 8 2 0 94 65535 0]Hm, I should probably take a[n]break from all the video games...[n][f 1 3 65535][w][e]
