[msg MORGANA_GAME_FAILED_TO_LOAD [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Hmm, looks like the game[n]doesn't want to load...[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]Maybe try blowing into the cartridge[n]and try again?[n][w][e]

[msg SYS_GAME_FAILED_TO_LOAD]
[s]The WAD you're trying to play[n]doesn't appear to be in the root directory.[n][w][e]
[s]Double-check that the appropriate WAD is[n]located in the game's root directory.[n][w][e]