[msg TUT_WADS_UNLOCKED_1 [WADs Unlocked]]
[s]Congrats on finishing DOOM Shareware![n]You can now purchase the full version of DOOM,[n]plus different WADs such as DOOM 2, FreeDOOM,[n]and even Chex® Quest![n][w][e]

[msg TUT_WADS_UNLOCKED_2 [WADs Unlocked]]
[s]Ensure that the DOOM 1 (DOOM.WAD)[n]and DOOM II: Hell on Earth (DOOM2.WAD) WADs[n][clr 10]are first[clr 0] in the DOOMSona directory [n]to play them.[n][w][e]