[msg DOOM_SHAREWARE_TUTORIAL_MSG01 [DOOM (Shareware)]]
[s]Welcome to the [clr 2]shareware version[clr 0] of DOOM![n]Enjoy the first episode, [clr 2]"Knee-Deep in the Dead"[clr 0].[n][w][e]

[msg DOOM_SHAREWARE_TUTORIAL_MSG02 [DOOM (Shareware)]]
[s]Complete this shareware on any difficulty, and you[n]will have the opportunity to buy the full version,[n]plus different WADs at the recycle shop![n][w][e]

[msg DOOM_SHAREWARE_TUTORIAL_MSG03 [DOOM (Shareware)]]
The DOOM 1 (DOOM.WAD) and[n]DOOM II: Hell on Earth (DOOM2.WAD) WADs[n][clr 10]must first[clr 0] be in the DOOMSona directory for them[n]to be playable.[n][w][e]

[msg DOOM_SHAREWARE_TUTORIAL_MSG04 [DOOM (Shareware)]]
[s]Key bindings can be edited via[n][clr 22]"chocolate-doom-setup.exe"[clr 0][n]in the DOOMSona directory![n][w][e]